Repository tripal/tripal_doc, pull requests merged in 2023-01, with the labels that each got.

#22 docker.rst add permission change step
  docs/install/docker.rst
Labels: TOPIC: Developer Hint, TOPIC: Building your site

#17 Docmentation for field creation
  docs/conf.py
  docs/design/pending/entities-fields/overview.rst
  docs/dev_guide/module_dev/alternate_databackend.rst
  docs/dev_guide/module_dev/entities.rst
  docs/dev_guide/module_dev/fields.rst
Labels: TOPIC: Building your site, API: Fields

#12 Add PR requirements to the docs
  docs/.gitignore
  docs/contributing.rst
  docs/contributing/communication.rst
  docs/contributing/contribution-guidelines.rst
  docs/contributing/contribution-guidelines.testcoverageexample.png
Labels: TOPIC: Tripal Community
