Repository tripal/tripal_doc, pull requests merged in 2024-04, with the labels that each got.

#68 More detailed instructions for traditional install
  docs/install/traditional.1.install_step_1.png
  docs/install/traditional.1.language.jpg
  docs/install/traditional.2.install_step_4.png
  docs/install/traditional.2.profile.jpg
  docs/install/traditional.3.enable_tripal.png
  docs/install/traditional.4.database.jpg
  docs/install/traditional.5.install.jpg
  docs/install/traditional.6.configure.jpg
  docs/install/traditional.7.installed.jpg
  docs/install/traditional.enable-tripal.1.jpg
  docs/install/traditional.enable-tripal.2.jpg
  docs/install/traditional.enable-tripal.3.jpg
  docs/install/traditional.prereq.apache.jpg
  docs/install/traditional.rst
Labels: TOPIC: Building your site

#71 Add information about the testing environments.
  docs/dev_guide/testing.rst
  docs/dev_guide/testing/chadoTestTrait.rst
  docs/dev_guide/testing/tripalTestTrait.rst
Labels: TOPIC: Extending Tripal

#73 Add a database backup and restore section
  docs/admin_guide.rst
  docs/admin_guide/database_backups.rst
Labels: TOPIC: Site administration
