Repository tripal/tripal_doc, pull requests merged in 2024-09, with the labels that each got.

#88 Documentation for migrating chado
  docs/upgrade_guide/site.rst
  docs/upgrade_guide/site/migrating_chado.rst
Labels: TOPIC: Upgrading Tripal

#92 Update TripalDocker docs and add in VScode Dev Container information.
  docs/contributing.rst
  docs/contributing/docker-for-testing.rst
  docs/contributing/vscode-devcontainer.rst
  docs/contributing/vscode.devcontainer.Intelephense.codeCompletion.png
  docs/contributing/vscode.devcontainer.Intelephense.gotoDefinition.1.png
  docs/contributing/vscode.devcontainer.Intelephense.gotoDefinition.2.png
  docs/contributing/vscode.devcontainer.Intelephense.signature.png
  docs/contributing/vscode.devcontainer.commandpalette.png
  docs/contributing/vscode.devcontainer.notification.png
  docs/contributing/vscode.devcontainer.ports.1.png
  docs/contributing/vscode.devcontainer.ports.2.png
  docs/contributing/vscode.devcontainer.statusIcon.png
  docs/contributing/vscode.devcontainer.terminal.drush.png
  docs/install/docker.rst
Labels: TOPIC: Developer Hint

#95 copyright year automatically updated
  docs/conf.py
Labels: general maintenance
