Repository tripal/tripal_doc, pull requests merged in 2024-03, with the labels that each got.

#62 Update supported version badges for Drupal 10.2
  docs/install/requirements.rst
Labels: TOPIC: Building your site

#61 How to Write an Importer
  docs/dev_guide/biodata.rst
  docs/dev_guide/biodata/chado.rst
  docs/dev_guide/biodata/custom_data_loader.0.png
  docs/dev_guide/biodata/custom_data_loader.1.png
  docs/dev_guide/biodata/custom_data_loader.2.png
  docs/dev_guide/biodata/importers.rst
Labels: TOPIC: Hands-on tutorial

#59 Adds documentation of Custom Tables.
  docs/dev_guide/biodata.rst
  docs/dev_guide/biodata/custom_tables.rst
  docs/dev_guide/lessons.rst
  docs/dev_guide/lessons/custom_tables.rst
Labels: TOPIC: Hands-on tutorial

#63 Update docs for tripal PR #1821
  docs/contributing/docker-for-testing.rst
  docs/install/docker.rst
  docs/install/requirements.rst
Labels: TOPIC: Tripal Community

#66 Very basic expansion to automated testing docs
  docs/dev_guide/testing.rst
  docs/dev_guide/testing/fields.rst
  docs/dev_guide/testing/fields/chadoStorage.rst
Labels: TOPIC: Extending Tripal
